---
title: "DNA oxidative damage analysis"
author: "MAthias Wegner"
date: "4/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read data

```{r cars}
setwd('~/Documents/Publication/DNA_Damage_Stickleback/')

library("tidyverse")

dna_damage.data = read_csv("stickleback_heart_DNA_damage_oxidative.csv")
```

fitting model with interaction

```{r pressure, echo=FALSE}
dna_damage.mod = dna_damage.data %>%
  lm(rel_amount ~ P_temp * O_temp, data = .)

summary(dna_damage.mod)
anova(dna_damage.mod)
```
-> nothing significant
-> generous interpretation, is that P18.5 has higher damage (p=0.12) but P21 lower (but very unsignificant p = 0.78), O21 might induce a bit more damage (p = 0.38)

fit model without interaction
```{r}
dna_damage.mod_noX = dna_damage.data %>%
  lm(rel_amount ~ P_temp + O_temp, data = .)

summary(dna_damage.mod_noX)
anova(dna_damage.mod_noX)
```
-> effects get a bit stronger, but still far away from significant


plot data
```{r}
ggplot(data = dna_damage.data,aes(x = treatment,y = rel_amount, color = O_temp)) +
  theme_classic() +
  geom_violin(width = 1.5) +
  geom_boxplot(width = 0.1)+
  stat_summary(fun.data=mean_sdl, mult=1,  geom="pointrange", color="black")

```

